server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: course-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://carol-course-db.mysql.database.azure.com/course_service?useTimezone=true&serverTimezone=UTC
    username: caag
    password: Carolina76
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: course_service
    user: root
    password: carolina

